# Расчет метрик

## Реализованные метрики

Под метрикой понимается некоторое числовое значение характеризующее один или несколько параметров реагирования пожарных подразделений.

В работе реализованы следующие метрики:

**time_max** -- Время следования из точки размещения подразделения до наиболее удаленного рассматриваемого узла ГДС.

**time_mean** -- Среднее время прибытия подразделения в любой рассматриваемый узел ГДС.

**time_median** -- Медианное время прибытия подразделения в любой рассматриваемый узел ГДС.

**ИП-10** -- Отношение количества рассматриваемых узлов ГДС время прибытия в которые не превышает 10 минут.

**ИП-20** -- Отношение количества рассматриваемых узлов ГДС время прибытия в которые не превышает 20 минут.

В зависимости от задач расчета метрики могут определяться для различных моделей. Так, например, ИП-10 может быть применен ко всем узлам ГДС, а может быть применен только к размещенным на территории района выезда объектам.

## Базовая функция расчета метрик

Основной реализованной функцией расчета стандартных метрик является функция calc_metric.

```{.python}
def calc_metric(E:Environment, 
                    node:int, 
                    path_function, 
                    metric_function, 
                    weight: str = "travel_time",
                    precision: int = 2):
```

Аргументы:

`E`:Environment, 
    Окружение.

`node`:int
    Узел для которого производится расчет

`path_function`: function
    Функция расчета кратчайших путей от единственного источника. 
    В качестве функции могут быть переданы реализации алгоритмов из пакета
    `networkx`. Например, реализация алгоритма Дейкстры: `nx.single_source_dijkstra_path_length`.
    Рекомендуется использовать функции указанные в `swiss_knife.ssfpl`.
    Пользователь может использовать собственные функции с
    интерфейсом `func(G: Graph, source: Any, cutoff: Any | None = None, weight: str = "weight")`

`metric_function`: function
    Целевая функция расчета метрики. 
    В качестве функции могут быть переданы статистические функции пакета numpy,
    такие как `np.max`, `np.mean` и т.д. А т.ж. функция `Metrics.calc_ip`.
    Кроме того пользователь может использовать собственные функции с
    интерфейсом `func(route_times:pd.Series)`

`weight`:str или function
    Имя поля содержащего вес ребер, или функция позволяющая вычислять 
    вес динамически.

`precision`: int 
    Точность округления

Возвращает:

`metric_val`: float
    Значение целевой метрики

## Примеры расчета

Создание модели окружения на основе некоторого ГДС `G`:

```{.python}
from genesis.calculators import Metrics
from genesis.swiss_knife import ssfpl
from genesis.models import Environment
import numpy as np

E = Environment(G)
```

:::{.callout-important}
# Важно

ГДС `G` должен быть предварительно подвергнут расчету времени следования для ребер. См. [[gds.qmd]]. После расчета для ребер ГДС будет добавлен атрибут `travel_time`, содержащий время следования.

В случае, если по каким либо причинам требуется при расчете использовать в качестве веса ребер значения из поля с отличным от `travel_time` названием, его можно указать явным образом при вызове функции `calc_metric(..., weight='имя поля')`.
:::

Расчет времени следования до наиболее удаленного узла:

```{.python}
Metrics.calc_metric(E, node=1, path_function=ssfpl, metric_function=np.max)
```

Расчет среднего времени прибытия в любой из узлов, с точностью до 4 знаков после'.':

```{.python}
Metrics.calc_metric(E, node=1, path_function=ssfpl, metric_function=np.mean,
    precision=4)
```

Расчет ИП-20, по полю 'edge_weight':

```{.python}
Metrics.calc_metric(E, node=1, path_function=ssfpl, metric_function=Metrics.calc_ip(ip_val=20),
    weight='edge_weight')
```

## Переопределение базовой функции

В случаях, когда имеющегося функционала не достаточно, функция может быть заменена
пользовательской функцией с интерфейсом:

```{.python}
def I_calc_metric(E:Environment, **kwargs): float
```

Пример:

Расчет доли узлов расположенных на расстоянии менее 1 км от стартовой точки, от общего количества узлов в ГДС.

```{.python}
def calc_metric(E:Environment, 
                    node:int, 
                    **kwargs):
    route_lens = nx.single_source_dijkstra_path_length(
        E.G, node, weight='length'
        )
    less_1000 = [1 if d<1000 else 0 for d in route_lens.values()]
    return round(sum(less_1000)/len(less_1000), 2)

# Применение:
metric_value = calc_metric(E, start_node)
```