# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GPKGGraphBuilder
                                 A QGIS plugin
 Плагин для проверки алгоритмов восстановления графа
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-29
        copyright            : (C) 2024 by SIBPSA
        email                : malyutin@sibpsa.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'SIBPSA'
__date__ = '2024-10-29'
__copyright__ = '(C) 2024 by SIBPSA'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GPKGGraphBuilder class from file GPKGGraphBuilder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .graph_builder import GPKGGraphBuilderPlugin
    return GPKGGraphBuilderPlugin()
