# Обсуждение (закрытая часть)

Здесь рассматриваются некоторые технические моменты и соображения, едва ли представляющие интерес конечному пользователю, но которые представляют интерес с точки зрения разработки системы.



## Представление архитектуры библиотеки genesis на 18.05.2024

Принцип разделения функций библиотеки: распределение функций по задачам:

genesis:

    - EAPP
        - время прибытия первого подразделения (first unit arrival time)
        - индекс прикрытия (cover index)
    - OSAP
        - определение границ районов выезда за счет построения леса Вороного (корректный, с учетом возможности наличия несвязных компонентов и объектов)
    - MCLP
        - Задача определения оптимального размещения одного подразделения пожарной охраны
        - Задача определения оптимального размещения множества подразделений пожарной охраны (с ограничением перемещения некоторых подразделений или без)
    - LSCP
        - Задача определения общего количества подразделений без учета существующих подразделений
        - Задача определения дополнительного количества подразделений по отношению к имеющемуся
        - Задача оценки излишних подразделений (тех которые можно удалить без неприемлемой потери степени защиты)
    - RNGFP
        - Наложение сети
        - Связывание несвязных компонентов
        - Разбиение графа полигоном границ (Получение зон обслуживания по фактическим границам зон обслуживания)
    - RNGIO
        - Получение графа из редактора QGIS
    - SP
        - Установка скоростей следования
    - tools
        - Преобразование км/ч->м/мин и т.д.
        - Получение всех соседних узлов и т.д.
        - Кастомный ProgressBar
