# Структура библиотеки



`
genesis
| best_points.py
| core.py
| mclp.py
| metrics.py
| state.py
| swiss_knife.py
| tools.py
`


В пакете `core.py` хранятся базовые классы используемые приложением.

В пакетах `metrics.py`, `state.py`, `best_points.py` хранятся основные реализации библиотеки Генезис (полученные в рамках работы "НИР Дислокация 2022").

При кастомизации возможны два подхода:

1. Написание собственного решения с использованием базовых классов `MetricBase`, `StateBase`, `BestPoints` и т.д.
2. Доработка для своих нужд классов реализации из пакетов `metrics.py`, `state.py`, `best_points.py`.


## core.py

Основные классы библиотеки


## metrics.py

Реализация функций метрик


## state.py

Реализация основных алгоритмов расчета состояния среды.


## best_points.py

Реализация алгоритмов поиска оптимальных узлов графа. Здесь например полный перебор, hill climbing, обезьяний алгоритм и т.д.


## mclp.py

Реализация алгоритмов поиска оптимального размещения нескольких наилучшим образом расположенных узлов (MCLP). Здесь например ГА.