project:
  type: book
  output-dir: documentation

book:
  title: "genesis docs"
  description: |
    Документация библиотеки genesis
  version: 0.0.1
  author: "Малютин О.С., Матеров Е.Н., Бабенышев С.В."
  date: today
  repo-url: https://github.com/Obsidian-pb/genesis
  repo-actions: [edit]
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    
    - pages/010_installation.qmd
    - pages/020_rapid_start.ipynb
    - pages/910_short.qmd
    - pages/920_terms.qmd
    - pages/900_references.qmd

    - 999_discussion.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



