project:
  type: book
  output-dir: documentation

book:
  title: "genesis docs"
  description: |
    Документация библиотеки genesis
  version: 0.0.1
  author: "Малютин О.С., Матеров Е.Н., Бабенышев С.В."
  date: today
  repo-url: https://github.com/Obsidian-pb/genesis
  repo-actions: [edit]
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - pages/structure.qmd
    - pages/rapid_start.qmd
    - pages/installation.qmd
    - part: pages/usage.qmd           # Тут описывается применение библиотеки
      chapters:
      - pages/usage/environment_usage.qmd
      - pages/usage/gds_usage.qmd
      - pages/usage/metrics_calc.qmd
    - part: pages/documentation.qmd         # Тут документация по алгоритмам (описание того как что считается)
      chapters:
      - pages/documentation/algorithms.qmd
    - pages/terms.qmd
    - pages/references.qmd
    - pages/discussion.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



